update experiments container

diff --git a/container b/container
--- a/container
+++ b/container
@@ -1,10 +1,11 @@
 #!/bin/bash
 BASEDIR="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
-IMAGE_NAME="crepair"
+IMAGE_NAME="crepair:experiments"
 CONTAINER_NAME="crepair_container"
 
 if [[ "$(docker images -q $IMAGE_NAME 2> /dev/null)" == ""  ]]; then
-  docker build -t $IMAGE_NAME .
+  echo "Docker Image crepair:experiments not found"
+  exit 1
 fi
 
 
